// Code generated by Slice Machine. DO NOT EDIT.

import CodeBlock from './CodeBlock';
import HeroBanner from './HeroBanner';
import ImageContent from './ImageContent';
import PostContent from './PostContent';

export {
	CodeBlock,
	HeroBanner,
	ImageContent,
	PostContent,
};

export const components = {
	code_block: CodeBlock,
	hero_banner: HeroBanner,
	image_content: ImageContent,
	post_content: PostContent,
};
