// Code generated by Slice Machine. DO NOT EDIT.

import HeroBanner from './HeroBanner';
<<<<<<< HEAD
import ImageContent from './ImageContent';
=======
import Image from './Image';
>>>>>>> f1f2b09447b0b2b567e2da03868d9bb4ce028371
import PostContent from './PostContent';

export {
	HeroBanner,
<<<<<<< HEAD
	ImageContent,
=======
	Image,
>>>>>>> f1f2b09447b0b2b567e2da03868d9bb4ce028371
	PostContent,
};

export const components = {
	hero_banner: HeroBanner,
<<<<<<< HEAD
	image_content: ImageContent,
=======
	image: Image,
>>>>>>> f1f2b09447b0b2b567e2da03868d9bb4ce028371
	post_content: PostContent,
};
