// Code generated by Slice Machine. DO NOT EDIT.

import HeroBanner from './HeroBanner';
import ImageContent from './ImageContent';
import PostContent from './PostContent';

export {
	HeroBanner,
	ImageContent,
	PostContent,
};

export const components = {
	hero_banner: HeroBanner,
	image_content: ImageContent,
	image: Image,
	post_content: PostContent,
};
